apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv-lun-0-frigate-media
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: iscsi
  iscsi:
    targetPortal: {{ .Values.iscsi.targetPortal }}
    iqn: {{ .Values.iscsi.iqn }}
    lun: 0
    fsType: ext4
    readOnly: false

